### ISSUE TITLE
Update connection string parameter

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-dl#57]
https://github.com/dag-hammarskjold-library/dlx-dl/blob/86193d908c159326fb0dbb4571823003a6c547ad/dlx_dl/scripts/sync/__init__.py#L65

Anywhere this line appears in the script, we just need to update 'connect-string' with 'prodISSU-admin-connect-string'; additionally, we need to specify the database name now, e.g., `DB.connect(connect_string, database=dbname)`

And finally, we should make sure we're pulling from the latest dlx version.
```[tasklist]
### Tasks
- [ ] Update connect-string in export
- [ ] Add database name to export
- [ ] Update connect-string to sync
- [ ] Add database name to sync
```
